name: CD

on:
  release:
    types: [ created ]

jobs:
  publish-maven-artifact:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      env:
        OSSRHUSER: ${{ secrets.OSSRHUSER }}
        OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
        GITHUB_VERSION: ${{ github.event.release.tag_name }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
